import { Listing } from "./types";

/**
 * Commute hubs are pre-computed per listing so the match engine never needs
 * live maps data. Values are illustrative but internally consistent with
 * real Pune geography (Hinjewadi = IT corridor west, Kharadi/Koregaon Park =
 * IT + social east, Viman Nagar = airport-adjacent, Kothrud/Baner = residential).
 */
export const mockListings: Listing[] = [
  {
    id: "listing-a-baner-heights",
    name: "Baner Heights",
    locality: "Baner",
    city: "Pune",
    monthlyRentTotal: 42000,
    hasLift: false,
    floor: 3,
    totalFloors: 4,
    bathrooms: 2,
    petFriendly: true,
    hasParking: true,
    hasBalcony: true,
    furnishing: "semi-furnished",
    commuteMinutes: {
      hinjewadi: 18,
      kharadi: 42,
      koregaonPark: 35,
      baner: 3,
      kothrud: 15,
      viman_nagar: 38,
    },
    coordinates: { lat: 18.562, lng: 73.7848 },
    distanceToMetroKm: 2.1,
    distanceToGymKm: 0.6,
    imageEmoji: "🏢",
    description:
      "A breezy 3rd-floor walk-up in a quiet Baner lane, close to the gym belt but no lift in the building.",
  },
  {
    id: "listing-b-wakad-residency",
    name: "Wakad Residency",
    locality: "Wakad",
    city: "Pune",
    monthlyRentTotal: 39000,
    hasLift: true,
    floor: 2,
    totalFloors: 6,
    bathrooms: 2,
    petFriendly: true,
    hasParking: true,
    hasBalcony: true,
    furnishing: "unfurnished",
    commuteMinutes: {
      hinjewadi: 50,
      kharadi: 55,
      koregaonPark: 48,
      baner: 12,
      kothrud: 22,
      viman_nagar: 52,
    },
    coordinates: { lat: 18.5987, lng: 73.7645 },
    distanceToMetroKm: 3.4,
    distanceToGymKm: 1.8,
    imageEmoji: "🏘️",
    description:
      "Spacious and lift-equipped, but tucked far from Hinjewadi with a long commute for anyone working that corridor.",
  },
  {
    id: "listing-c-kothrud-comfort",
    name: "Kothrud Comfort Homes",
    locality: "Kothrud",
    city: "Pune",
    monthlyRentTotal: 45000,
    hasLift: true,
    floor: 1,
    totalFloors: 5,
    bathrooms: 2,
    petFriendly: true,
    hasParking: true,
    hasBalcony: true,
    furnishing: "semi-furnished",
    commuteMinutes: {
      hinjewadi: 22,
      kharadi: 38,
      koregaonPark: 30,
      baner: 15,
      kothrud: 2,
      viman_nagar: 34,
    },
    coordinates: { lat: 18.5096, lng: 73.8088 },
    distanceToMetroKm: 0.8,
    distanceToGymKm: 1.2,
    imageEmoji: "🏡",
    description:
      "Ground-adjacent first floor with lift, metro nearby, and a comfortable middle-ground commute for the Hinjewadi crowd.",
  },
  {
    id: "listing-d-viman-vista",
    name: "Viman Vista Apartments",
    locality: "Viman Nagar",
    city: "Pune",
    monthlyRentTotal: 48000,
    hasLift: true,
    floor: 5,
    totalFloors: 9,
    bathrooms: 3,
    petFriendly: false,
    hasParking: true,
    hasBalcony: false,
    furnishing: "fully-furnished",
    commuteMinutes: {
      hinjewadi: 45,
      kharadi: 12,
      koregaonPark: 15,
      baner: 32,
      kothrud: 34,
      viman_nagar: 3,
    },
    coordinates: { lat: 18.5709, lng: 73.9123 },
    distanceToMetroKm: 1.5,
    distanceToGymKm: 2.4,
    imageEmoji: "🏙️",
    description:
      "Premium, fully-furnished high floor with a lift, close to the airport belt but no balcony and not pet-friendly.",
  },
  {
    id: "listing-e-hinjewadi-central",
    name: "Hinjewadi Central Towers",
    locality: "Hinjewadi Phase 1",
    city: "Pune",
    monthlyRentTotal: 41000,
    hasLift: true,
    floor: 4,
    totalFloors: 12,
    bathrooms: 2,
    petFriendly: true,
    hasParking: true,
    hasBalcony: true,
    furnishing: "semi-furnished",
    commuteMinutes: {
      hinjewadi: 5,
      kharadi: 55,
      koregaonPark: 50,
      baner: 20,
      kothrud: 28,
      viman_nagar: 58,
    },
    coordinates: { lat: 18.5872, lng: 73.7412 },
    distanceToMetroKm: 4.2,
    distanceToGymKm: 3.1,
    imageEmoji: "🌆",
    description:
      "Right in the IT corridor with a lift and balcony, but far from the metro line and a longer haul to the gym belt.",
  },
  {
    id: "listing-f-koregaon-charm",
    name: "Koregaon Park Charm",
    locality: "Koregaon Park",
    city: "Pune",
    monthlyRentTotal: 52000,
    hasLift: true,
    floor: 2,
    totalFloors: 4,
    bathrooms: 2,
    petFriendly: true,
    hasParking: false,
    hasBalcony: true,
    furnishing: "fully-furnished",
    commuteMinutes: {
      hinjewadi: 40,
      kharadi: 18,
      koregaonPark: 3,
      baner: 30,
      kothrud: 33,
      viman_nagar: 20,
    },
    coordinates: { lat: 18.5384, lng: 73.8918 },
    distanceToMetroKm: 1.1,
    distanceToGymKm: 0.9,
    imageEmoji: "🌳",
    description:
      "Leafy, lift-equipped and fully furnished with no dedicated parking, priced at a premium for the location.",
  },
  {
    id: "listing-g-kharadi-nest",
    name: "Kharadi Nest",
    locality: "Kharadi",
    city: "Pune",
    monthlyRentTotal: 37000,
    hasLift: true,
    floor: 3,
    totalFloors: 7,
    bathrooms: 1,
    petFriendly: true,
    hasParking: true,
    hasBalcony: true,
    furnishing: "unfurnished",
    commuteMinutes: {
      hinjewadi: 48,
      kharadi: 4,
      koregaonPark: 14,
      baner: 36,
      kothrud: 40,
      viman_nagar: 16,
    },
    coordinates: { lat: 18.5493, lng: 73.9367 },
    distanceToMetroKm: 5.5,
    distanceToGymKm: 2.8,
    imageEmoji: "🐦",
    description:
      "Budget-friendly with a lift, but only a single bathroom and far from the metro corridor.",
  },
  {
    id: "listing-h-baner-budget",
    name: "Baner Budget Stay",
    locality: "Baner",
    city: "Pune",
    monthlyRentTotal: 33000,
    hasLift: true,
    floor: 1,
    totalFloors: 3,
    bathrooms: 2,
    petFriendly: false,
    hasParking: false,
    hasBalcony: false,
    furnishing: "unfurnished",
    commuteMinutes: {
      hinjewadi: 16,
      kharadi: 44,
      koregaonPark: 36,
      baner: 2,
      kothrud: 14,
      viman_nagar: 40,
    },
    coordinates: { lat: 18.5566, lng: 73.7891 },
    distanceToMetroKm: 2.5,
    distanceToGymKm: 0.5,
    imageEmoji: "💰",
    description:
      "The cheapest option in Baner with a lift, but no balcony, no parking, and not pet-friendly.",
  },
  {
    id: "listing-i-kothrud-family",
    name: "Kothrud Family Enclave",
    locality: "Kothrud",
    city: "Pune",
    monthlyRentTotal: 44000,
    hasLift: true,
    floor: 2,
    totalFloors: 6,
    bathrooms: 3,
    petFriendly: true,
    hasParking: true,
    hasBalcony: true,
    furnishing: "semi-furnished",
    commuteMinutes: {
      hinjewadi: 25,
      kharadi: 36,
      koregaonPark: 28,
      baner: 16,
      kothrud: 4,
      viman_nagar: 32,
    },
    coordinates: { lat: 18.5051, lng: 73.8055 },
    distanceToMetroKm: 1.4,
    distanceToGymKm: 1.6,
    imageEmoji: "👨‍👩‍👧",
    description:
      "Family-friendly enclave with three bathrooms, a lift, and a balanced commute profile across the city.",
  },
  {
    id: "listing-j-viman-value",
    name: "Viman Nagar Value Homes",
    locality: "Viman Nagar",
    city: "Pune",
    monthlyRentTotal: 36000,
    hasLift: false,
    floor: 2,
    totalFloors: 3,
    bathrooms: 2,
    petFriendly: true,
    hasParking: true,
    hasBalcony: true,
    furnishing: "unfurnished",
    commuteMinutes: {
      hinjewadi: 46,
      kharadi: 14,
      koregaonPark: 16,
      baner: 34,
      kothrud: 36,
      viman_nagar: 4,
    },
    coordinates: { lat: 18.5648, lng: 73.9174 },
    distanceToMetroKm: 2.9,
    distanceToGymKm: 3.5,
    imageEmoji: "✈️",
    description:
      "Good value near the airport belt, but a walk-up building with no lift and a longer gym commute.",
  },
];
